BettingApp/Areas/Admin/Controllers/CurrencyController.cs
using BettingApp.Core.Contracts;
using BettingApp.Core.Models.Currency;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using static BettingApp.Areas.Admin.AdminConstants;

namespace BettingApp.Areas.Admin.Controllers
{
    [Area(AreaName)]
    [Authorize(Roles = AdminRoleName)]
    public class CurrencyController : Controller
    {
        private readonly ICurrencyService currencyService;
        private readonly IMemoryCache cache;

        public CurrencyController(ICurrencyService _currencyService, IMemoryCache _cache)
        {
            currencyService = _currencyService;
            cache = _cache;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var currencies = await currencyService.AllAsync();

            var cacheOptions = new MemoryCacheEntryOptions()
                .SetAbsoluteExpiration(TimeSpan.FromMinutes(1440));
             
            cache.Set(CurrenciesCacheKey, currencies, cacheOptions);

            return View(currencies);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string ISOCode)
        {
            return View(await currencyService.ByCodeAsync(ISOCode));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CurrencyModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await currencyService.EditAsync(model);
            cache.Remove(CurrenciesCacheKey);
            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View(new CurrencyModel());
        }

        [HttpPost]
        public async Task<IActionResult> Add(CurrencyModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await currencyService.CreateAsync(model);
            cache.Remove(CurrenciesCacheKey);
            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string ISOCode)
        {
            await currencyService.DeleteAsync(ISOCode);
            cache.Remove(CurrenciesCacheKey);
            return RedirectToAction(nameof(All));
        }
    }
}

BettingApp/Areas/Admin/Views/Currency/Add.cshtml
@model CurrencyModel

@{
    ViewData["Title"] = "Add";
}

<h1>Add</h1>

<h4>Currency</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ISOCode" class="control-label"></label>
                <input asp-for="ISOCode" class="form-control" />
                <span asp-validation-for="ISOCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortDescription" class="control-label"></label>
                <input asp-for="ShortDescription" class="form-control" />
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExchangeRate" class="control-label"></label>
                <input asp-for="ExchangeRate" class="form-control" />
                <span asp-validation-for="ExchangeRate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="All">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BettingApp/Areas/Admin/Views/Currency/All.cshtml
@model IEnumerable<CurrencyModel>

@{
    ViewBag.Title = "All Currencies";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />
<a class="btn btn-primary text-center" asp-controller="Currency" asp-action="Add">Create New</a>
<table class="table table-striped">
    <thead>
        <tr>
            <th><label>Code</label></th>
            <th><label>Description</label></th>
            <th><label>Short Description</label></th>
            <th><label>Exchange Rate</label></th>
            <th><label>Date Time Updated</label></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var currency in Model)
        {
            <tr>
                <td><label>@currency.ISOCode</label></td>
                <td><label>@currency.Description</label></td>
                <td><label>@currency.ShortDescription</label></td>
                <td><label>@currency.ExchangeRate</label></td>
                <td><label>@currency.DateTime</label></td>
                <td><a asp-controller="Currency" asp-action="Edit" asp-route-ISOCode="@currency.ISOCode" class="btn btn-primary">Edit</a></td>
                <td><a asp-controller="Currency" asp-action="Delete" asp-route-ISOCode="@currency.ISOCode" class="btn btn-primary">Delete</a></td>
            </tr>
        }
    </tbody>
</table>

BettingApp/Areas/Admin/Views/Currency/Edit.cshtml
@model CurrencyModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Currency</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ISOCode" />
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortDescription" class="control-label"></label>
                <input asp-for="ShortDescription" class="form-control" />
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExchangeRate" class="control-label"></label>
                <input asp-for="ExchangeRate" class="form-control" />
                <span asp-validation-for="ExchangeRate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="All">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}