BettingApp/Controllers/BetController.cs
using BettingApp.Core.Contracts;
using BettingApp.Core.Models.Bet;
using BettingApp.Core.Models.GameBet;
using BettingApp.Extensions;
using BettingApp.Infrastructure.Data.Common;
using BettingApp.Infrastructure.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace BettingApp.Controllers
{
    [Authorize]
    public class BetController : Controller
    {
        public readonly IUserService userService;
        public readonly IBetService betService;
        public readonly IRepository repo;

        public BetController(IUserService _userService, IBetService _betService, IRepository _repo)
        {
            userService = _userService;
            betService = _betService;
            repo = _repo;
        }

        [HttpPost]
        public async Task<IActionResult> PlaceBet(BetQueryModel model)
        {
            var balance = userService.GetBalance(User.Id());
            if (!ModelState.IsValid || model.Amount > balance)
            {
                TempData["ErrorMessage"] = "Invalid Amount!";

                return RedirectToAction("Index", "Home");
            }

            model.GameBets = await GetBetsFromSessionStorage();

            await betService.CreateBetAsync(model, User.Id());

            ClearBetsFromSessionStorage();

            return RedirectToAction("UserBets", "User");
        }
        public async Task<List<GameBetViewModel>> GetBetsFromSessionStorage()
        {
            string? gameBetsString = HttpContext.Session.GetString("GameBets");
            var gameBets = new List<GameBetViewModel>();
            if (gameBetsString != null)
            {
                gameBets = JsonSerializer.Deserialize<List<GameBetViewModel>>(gameBetsString)
                    ?? new List<GameBetViewModel>();
            }
            foreach (var gameBet in gameBets)
            {
                var game = await repo.GetByIdAsync<Game>(gameBet.GameId);
                if (game.DateTime < DateTime.Now)
                {
                    gameBets.Remove(gameBet);
                }
            }
            return gameBets;
        }

        public void ClearBetsFromSessionStorage()
        {
            HttpContext.Session.Remove("GameBets");
        }

        [HttpGet]
        public async Task<ActionResult> GetBetDetails(int betId)
        {
            return PartialView("_BetDetailsPartial", await betService.GetGameBets(betId));
        }

        [HttpPost]
        public async Task<IActionResult> Cancel(int id)
        {
            await betService.CancelBet(id);

            return RedirectToAction("UserBets", "User");
        }
    }
}

BettingApp/Controllers/CompetitionController.cs
using BettingApp.Core.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace BettingApp.Controllers
{
    public class CompetitionController : Controller
    {
        private readonly ICompetitionService competitionService;

        public CompetitionController(ICompetitionService _competitionService)
        {
            competitionService = _competitionService;
        }

        [Route("{controller}/{id}/Standings")]
        public async Task<IActionResult> Standings(int id)
        {
            var model = await competitionService.Standings(id);
            return View(model);
        }
    }
}

BettingApp/Controllers/GameController.cs
using BettingApp.Core.Contracts;
using BettingApp.Core.Models.Game;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static BettingApp.Areas.Bookmaker.BookmakerConstants;
using static BettingApp.Areas.Admin.AdminConstants;

namespace BettingApp.Controllers
{
    public class GameController : Controller
    {
        private readonly IGameService gameService;
        private readonly ITeamService teamService;
        private readonly ICompetitionService competitionService;

        public GameController(IGameService _gameService, ITeamService _teamService, ICompetitionService _competitionService)
        {
            gameService = _gameService;
            teamService = _teamService;
            competitionService = _competitionService;
        }

        [Area("Bookmaker")]
        [Authorize(Roles = $"{BookmakerRoleName},{AdminRoleName}")]
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var teams = await teamService.AllAsync();
            var competitions = await competitionService.GetAllAsync();

            var model = new GameFormModel()
            {
                Competitions = competitions,
                Teams = teams
            };

            return View(model);
        }

        [Area("Bookmaker")]
        [Authorize(Roles = $"{BookmakerRoleName},{AdminRoleName}")]
        [HttpPost]
        public async Task<IActionResult> Add(GameFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await gameService.CreateAsync(model);
            return RedirectToAction("Games", "Admin");
        }

        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            var model = new GameDetailsModel();
            model.Game = await gameService.DetailsByIdAsync(id);
            model.LastFiveHome = await gameService.LastNGames(5, model.Game.HomeTeam.Id);
            model.LastFiveAway = await gameService.LastNGames(5, model.Game.AwayTeam.Id);

            return View(model);
        }

        [Area("Bookmaker")]
        [Authorize(Roles = $"{BookmakerRoleName},{AdminRoleName}")]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await gameService.ByIdAsync(id);

            return View(model);
        }

        [Area("Bookmaker")]
        [Authorize(Roles = $"{BookmakerRoleName},{AdminRoleName}")]
        [HttpPost]
        public async Task<IActionResult> Edit(GameFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await gameService.EditAsync(model);

            return RedirectToAction(nameof(List));
        }

        [Area("Bookmaker")]
        [Authorize(Roles = $"{BookmakerRoleName},{AdminRoleName}")]
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await gameService.DeleteAsync(id);
            return RedirectToAction(nameof(List));
        }

        [HttpGet]
        public async Task<IActionResult> All([FromQuery] GameQueryModel query)
        {
            var result = await gameService.All(
                query.Upcoming,
                query.Results,
                query.TeamTerm,
                query.Competition,
                query.CurrentPage,
                GameQueryModel.GamesPerPage);

            query.TotalGamesCount = result.GamesCount;
            query.Games = result.Games;
            query.Competitions = await competitionService.GetAllAsync();

            return View(query);
        }

        [Area("Bookmaker")]
        [Authorize(Roles = $"{BookmakerRoleName},{AdminRoleName}")]
        [HttpGet]
        public async Task<IActionResult> List([FromQuery] GameQueryModel query)
        {
            var result = await gameService.All(
                query.Upcoming,
                query.Results,
                query.TeamTerm,
                query.Competition,
                query.CurrentPage,
                GameQueryModel.GamesPerPage);

            query.TotalGamesCount = result.GamesCount;
            query.Games = result.Games;
            query.Competitions = await competitionService.GetAllAsync();

            return View(query);
        }
    }
}

BettingApp/Controllers/TeamController.cs
using BettingApp.Core.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BettingApp.Controllers
{
    public class TeamController : Controller
    {
        private readonly ITeamService teamService;
        private readonly IGameService gameService;

        public TeamController(ITeamService _teamService, IGameService _gameService)
        {
            teamService = _teamService;
            gameService = _gameService;
        }

        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            var model = await teamService.DetailsByIdAsync(id);
            model.Games = await gameService.NextNGames(5, id);

            return View(model);
        }
    }
}

BettingApp/Views/Shared/_BetDetailsPartial.cshtml
@model IEnumerable<GameBetViewModel>

<table class=table>
    <thead>
        <tr>
            <th>Home Team</th>
            <th>Away Team</th>
            <th>Prediction</th>
            <th>Bet Rate</th>
            <th>Won</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var gameBet in Model)
        {
            <tr>
                <td>@gameBet.HomeTeam</td>
                <td>@gameBet.AwayTeam</td>
                <td>@gameBet.Prediction</td>
                <td>@gameBet.BetRate</td>
                <td>@gameBet.Won</td>
            </tr>
        }
    </tbody>
</table>

BettingApp/Views/Shared/_BetsPartial.cshtml
@model IEnumerable<BetViewModel>
@if(Model.Count() == 0)
{
    <h1 class="text-center">No bets found!</h1>
}
else
{
    <div class="container text-center">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.DateTime)
                    </th>
                    <th scope="col">
                        Number of games
                    </th>
                    <th scope="col">
                        Bet Rate
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.Amount)
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.CurrencyCode)
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.Closed)
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.WinAmount)
                    </th>
                    <th scope="col">
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach(var bet in Model)
                {
                    <tr>
                        <td>
                            @bet.DateTime
                        </td>
                        <td>
                            @bet.GamesCount
                        </td>
                        <td>
                            @bet.BetRate
                        </td>
                        <td>
                            @bet.Amount
                        </td>
                        <td>
                            @bet.CurrencyCode
                        </td>
                        <td>
                            @bet.Closed
                        </td>
                        <td>
                            @bet.WinAmount
                        </td>
                        <td>
                            <a id="@bet.Id" class="Details" href="javascript:;">Details</a>
                        </td>
                    </tr>
                }
        </table>
        <div id="partialModal" class="modal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Bet Details</h5>
                        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $(function() {
        $(".Details").click(function() {
            $.ajax({
                type: "GET",
                url: "/Bet/GetBetDetails",
                data: `{ betId: ${this.id} }`,
                contentType: "application/json; charset=utf-8",
                dataType: "html",
                success: function (response) {
                    $("#partialModal").find(".modal-body").html(response);
                    $("#partialModal").modal('show');
                },
                failure: function (response) {
                    alert(response.responseText);
                },
                error: function (response) {
                    alert(response.responseText);
                }
            });
        })
    })
</script>

BettingApp/Views/Shared/_EmployeeCardPartial.cshtml
@model EmployeeViewModel

<div class="card" style="width: 150px;">
    @if (Model.ImageUrl != null)
    {
        <img class="card-img-top" src="@Model.ImageUrl" style="height: 100px; width:150px"/>
    }
    <div class="card-body">
        <h4 class="card-title">@Model.FirstName @Model.LastName</h4>
        <p class="card-text text-center">
            @if (Model.CountryImageUrl != null)
            {
                <img src="@Model.CountryImageUrl" />
            }
            @Model.Country
        </p>
        <p class="card-text text-center">
            @Model.Position
        </p>
    </div>
</div>

BettingApp/Views/Shared/_GameBetsPartial.cshtml
<div id="betGrid" style="left: 30%; bottom: 1%; position:fixed; width: 40%">
    
</div>

BettingApp/Views/Shared/_GameBetsPartialData.cshtml
@model BetQueryModel

@if (Model.GameBets.Count() > 0)
{
    <div>
        <input id="betsCount" class="btn btn-primary" type="submit" onclick="showBets()" value="Bets: @Model.GameBets.Count()" style="width:100%">
    </div>

        <div id="betsTable" style="background-color:#f7f5ff" ; width: 50%; margin: 0 auto; display: block; text-align: center" hidden="hidden">
            <div style="color:black; right: 30%; position:fixed">
                <input type="submit" class="btn btn-primary" onclick="hideBets()" value="X">
            </div>
            <table class="table" width="90%">
                <thead>
                    <tr>
                        <th scope="col">Home</th>
                        <th scope="col">Away</th>
                        <th scope="col">Bet Rate</th>
                        <th scope="col">Prediction</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var gameBet in Model.GameBets)
                    {
                        <tr>
                            <td class="text-center">
                                @gameBet.HomeTeam
                            </td>
                            <td class="text-center">
                                @gameBet.AwayTeam
                            </td>
                            <td class="text-center">
                                @gameBet.BetRate
                            </td>
                            <td class="text-center">
                                @gameBet.Prediction
                            </td>
                            <td>
                                <input id="@gameBet.GameId" class="RemoveBet btn btn-primary" type="button" value="Remove">
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="container">
                <div class="row">
                    <div class="col-sm">
                        Total Bet Rate: 
                    </div>
                    <div class="col-sm">
                        @Model.GameBets.Select(gb => gb.BetRate).Aggregate((a,b) => a*b).ToString("0.00")
                    </div>
                </div>
                
                 <form id="placebetpartial" asp-controller="Bet" asp-action="PlaceBet" data-ajax="true" data-ajax-update="#placebetpartial" data-ajax-mode="update">
                    <div class="row">
                        <div class="col-sm">
                            <label asp-for="Amount"></label>
                        </div>
                        <div class="col-sm">
                            <input asp-for="Amount" class="form-control">
                            <span asp-validation-for="Amount" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <input type="submit" class="match-bet-place" value="Place Bet" />
                    </div>
                </form>
            </div>
        </div>
}


<script type="text/javascript">
    $(function() {
        $(".RemoveBet").click(function () {
            removeMarker(this.id);
            $.ajax({
                type: "DELETE",
                url: "/GameBet/Remove",
                data: {
                    __RequestVerificationToken: getToken(),
                    gameId: this.id
                },
                dataType: "html",
                success: function (response) {
                    $('#betGrid').html(response);
                    $('#betsTable').removeAttr("hidden");
                },
                failure: function (response) {
                    alert(response.responseText);
                },
                error: function (response) {
                    alert(response.responseText);
                }
            })
        })
    });
</script>

BettingApp/Views/Shared/_GameCardPartial.cshtml
@model GameViewModel
	<div class="container">
		<div class="match">
			<div class="match-header">
				
				@if(Model.Date > DateTime.Now)
				{
					<div class="match-status">Upcoming</div>
				}
				else
				{
					<div class="match-status">Finished</div>
				}
				
				<div class="match-tournament">
					@if (Model.Competition.ImageUrl != null)
					{
						<img src="@Model.Competition.ImageUrl" />
					}
				<a asp-area="" asp-controller="Competition" asp-action="Standings" asp-route-id="@Model.Competition.Id">@Model.Competition.Name</a>
				</div>
				<div class="match-actions">
				
				</div>
			</div>
			<div class="match-content">
				<div class="column">
					<a asp-action="Details" asp-controller="Team" asp-route-id="@Model.HomeTeam.Id">
						<div class="team team--home">
							<div class="team-logo">
								@if(Model.HomeTeam.ImageUrl != null)
								{
									<img src="@Model.HomeTeam.ImageUrl" />
								}
							</div>
							<h2 class="team-name">@Model.HomeTeam.Name</h2>
						</div>
					</a>
					
					@if ((User?.IsInRole("Bookmaker") ?? false) || (User?.IsInRole("Administrator") ?? false))
					{
						<button class="match-edit">
							<a asp-action="Edit" asp-route-id="@Model.Id" asp-controller="Game" asp-area="Bookmaker">
								Edit
							</a>
						</button>
					}
				</div>
				<div class="column">
					<div class="match-details" data-detailsgameid="@Model.Id">
						<div class="match-date">
							@Model.Date
						</div>
						@if (Model.Date > DateTime.Now)
						{
							@if(User?.Identity?.IsAuthenticated ?? false)
							{
								<div class="match-bet-options">
									<button class="match-bet-option home-bet" data-gameid="@Model.Id" data-prediction="1">@Model.HomeRate</button>
									<button class="match-bet-option draw-bet" data-gameid="@Model.Id" data-prediction="X"> @Model.DrawRate</button>
									<button class="match-bet-option away-bet" data-gameid="@Model.Id" data-prediction="2">@Model.AwayRate</button>
								</div>
							}
						}
						else
						{
							<div class="match-result">
								<h1 class="score">@Model.HomeGoals : @Model.AwayGoals</h1>
							</div>
						}
						@if(User?.Identity?.IsAuthenticated ?? false)
						{
							<a class="game-details" asp-action="Details" asp-controller="Game" asp-route-id="@Model.Id">
								Details
							</a>
						}
					</div>
				</div>
				<div class="column">
					<a asp-action="Details" asp-controller="Team" asp-route-id="@Model.AwayTeam.Id">
						<div class="team team--away">
							<div class="team-logo">
								@if (Model.AwayTeam.ImageUrl != null)
								{
									<img src="@Model.AwayTeam.ImageUrl" />
								}
						</div>
							<h2 class="team-name"> @Model.AwayTeam.Name</h2>
						</div>
					</a>
					@if((User?.IsInRole("Bookmaker") ?? false) || (User?.IsInRole("Administrator") ?? false))
					{
						<button class="match-delete">
							<a asp-action="Delete" asp-route-id="@Model.Id" asp-controller="Game" asp-area="Bookmaker">
								Delete
							</a>
						</button>
					}
				</div>
			</div>
		</div>
	</div>

BettingApp/Views/Shared/_GamesPartial.cshtml
@model IEnumerable<GameViewModel>
<div class="card">
    <div class="card-body">
        <h5 class="card-title text-center">@ViewData["Label"]</h5>
        @foreach (var game in Model)
        {
            <a class="card-text text-center" asp-action="Details" asp-controller="Game" asp-route-id="@game.Id">
                <div class="row">
                    <div class="col">
                        <img src="@game.HomeTeam.ImageUrl" style="width: 20px; height: 20px; display:inline"/> 
                        @game.HomeTeam.Name 
                        @if (game.Date < DateTime.Now)
                        { 
                            @Html.Raw($"{@game.HomeGoals}:{@game.AwayGoals}")
                        }
                        else
                        {
                            @Html.Raw("-")
                        }
                        @game.AwayTeam.Name 
                        <img src="@game.AwayTeam.ImageUrl" style="width: 20px; height: 20px; display:inline"/>
                    </div>
                </div>
            </a>
        }
    </div>
</div>

BettingApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Football Betting</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BettingApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav id="nav" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BettingApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Game" asp-action="All" asp-area="" asp-route-upcoming="true">Games</a>
                        </li>
                        @if (User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index">Administration</a>
                            </li>
                        }
                        @if(User.IsInRole("Bookmaker") || User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Game" asp-action="List" asp-area="Bookmaker">Games List</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="bottom:0;left:0;position:relative;width:100%">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - BettingApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BettingApp/Views/Shared/_TeamCardPartial.cshtml
@model TeamViewModel

<div class="row">
    <div class="col text-sm-end">
        @if(Model.ImageUrl != null)
        {
            <img src="@Model.ImageUrl" alt="@Model.Name" style="display:inline"/>
        }
    </div>
    <div class="col text-sm-start">
        <h2>@Model.Name</h2>
        <br />
        <p class="title">@Model.Country</p>
    </div>
</div>

BettingApp/Views/Shared/_TransactionsPartial.cshtml
@model IEnumerable<TransactionModel>

@if(Model.Count() == 0)
{
    <h1 class="text-center">No transaction history!</h1>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.DateTime)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.TransactionType)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Amount)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.CurrencyCode)
                </th>
            </tr>
        </thead>
        <tbody>
        @foreach (var transaction in Model)
        {
            <tr>
                <td>
                    @transaction.DateTime
                </td>
                <td>
                    @transaction.TransactionType
                </td>
                <td>
                    @transaction.Amount
                </td>
                <td>
                    @transaction.CurrencyCode
                </td>
            </tr>
        }
        </tbody>
    </table>
}